# Workflow [no intendation required for naming workflow]
name: Hello

# On tells when the workflow should run (Give intendation by TAB)
on:
  workflow_dispatch:

#Job tells what the workflow should do, there can be one or more than one job, hence we write jobs
# Jobs is an object so needs intendation
jobs:
 
  # 1st Job (give intendation)
  say-hello:
  
    # Creates an Ephermal Container with Ubuntu running
    runs-on: ubuntu-latest

    
    # That ephermal container will have steps to execute, hence name those steps and use run: run has the command
     steps:
      - name: Say hello to everyone
        run: echo "Hello dosto"
